<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7kevl0r\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7kevl0r/appProdProjectContainer.php') {
    touch(__DIR__.'/Container7kevl0r.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container7kevl0r\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container7kevl0r\appProdProjectContainer([
    'container.build_hash' => '7kevl0r',
    'container.build_id' => '611e50fc',
    'container.build_time' => 1651049198,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7kevl0r');
