<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFttxokn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFttxokn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFttxokn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFttxokn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFttxokn\appProdProjectContainer([
    'container.build_hash' => 'Fttxokn',
    'container.build_id' => '0969e997',
    'container.build_time' => 1650972949,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFttxokn');
