<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWdu1jkb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWdu1jkb/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWdu1jkb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWdu1jkb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWdu1jkb\appProdProjectContainer([
    'container.build_hash' => 'Wdu1jkb',
    'container.build_id' => 'de719c3b',
    'container.build_time' => 1651057382,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWdu1jkb');
