<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUh8cb8m\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUh8cb8m/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUh8cb8m.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUh8cb8m\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUh8cb8m\appDevDebugProjectContainer([
    'container.build_hash' => 'Uh8cb8m',
    'container.build_id' => '6871393e',
    'container.build_time' => 1651144471,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUh8cb8m');
