<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC0rxphu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC0rxphu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerC0rxphu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerC0rxphu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerC0rxphu\appDevDebugProjectContainer([
    'container.build_hash' => 'C0rxphu',
    'container.build_id' => '0f9693e0',
    'container.build_time' => 1651130562,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC0rxphu');
